#!/bin/sh
BOT_ID=$(uci get telegram.bot.bot_id) 
CHAT_ID=$(uci get telegram.bot.chat_id)
if [ $# -gt 0 ]
then
    TEXT=$*
else
    TEXT=$(cat -)
fi
curl -s -X POST -d chat_id=${CHAT_ID} -d text="$TEXT" -d disable_notification=true https://api.telegram.org/bot${BOT_ID}/sendMessage
